#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "src" / "app" / "page-registry.json"
INDEX_PATH = REPO_ROOT / "index.html"


def load_registry(path: Path = REGISTRY_PATH) -> dict[str, object]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def escape(value: object) -> str:
    return html.escape(str(value), quote=True)


def render_page_number(number: int) -> str:
    return f"{number:02d}"


def nav_class(page: dict[str, object], is_active: bool) -> str:
    if page.get("navGroup") == "practice":
        accent = page.get("navAccent")
        if accent == "red":
            return (
                "nav-item text-red-600 bg-white border border-gray-200 shadow-sm "
                "hover:border-red-300 hover:text-red-600"
            )
        return (
            "nav-item text-blue-600 bg-white border border-gray-200 shadow-sm "
            "hover:border-blue-300 hover:text-blue-600"
        )
    return "nav-item active" if is_active else "nav-item"


def render_nav_button(page: dict[str, object], is_active: bool) -> str:
    number = int(page["number"])
    title = page.get("navTitle") or page["title"]
    classes = nav_class(page, is_active)

    if page.get("navGroup") == "practice":
        icon = page.get("navIcon")
        icon_html = f'<span class="mr-3 text-lg">{escape(icon)}</span>' if icon else ""
        return (
            f'                    <button type="button" class="{classes}" data-go-page="{number}">'
            f"{icon_html} {number} {escape(title)}</button>"
        )

    return (
        f'                <button type="button" class="{classes}" data-go-page="{number}">'
        f'<span class="text-gray-400 font-mono text-xs w-6 mr-1">{render_page_number(number)}</span> '
        f"{escape(title)}</button>"
    )


def render_nav(pages: list[dict[str, object]]) -> str:
    lines: list[str] = []
    practice_group_open = False

    for index, page in enumerate(pages):
        is_practice = page.get("navGroup") == "practice"
        if is_practice and not practice_group_open:
            lines.append('                <div class="pt-6 mt-6 border-t border-gray-200 space-y-2">')
            practice_group_open = True
        if not is_practice and practice_group_open:
            lines.append("                </div>")
            practice_group_open = False

        lines.append(render_nav_button(page, is_active=index == 0))

    if practice_group_open:
        lines.append("                </div>")

    return "\n".join(lines)


def render_page_frame(page: dict[str, object], is_active: bool) -> str:
    page_id = escape(page["id"])
    title = escape(page.get("frameTitle") or page["title"])
    source = escape(page["src"])
    loading_text = escape(page.get("loadingText") or f"{page['title']} 페이지를 불러오는 중입니다...")
    active_class = " active" if is_active else ""

    return f"""
<section class="page-section{active_class}" id="{page_id}">
    <div class="page-frame-shell" data-page-shell>
        <div class="page-frame-loading">{loading_text}</div>
        <iframe
            class="page-frame"
            title="{title}"
            data-page-frame
            data-page-id="{page_id}"
            data-page-src="{source}"
            loading="lazy"
        ></iframe>
    </div>
</section>""".strip()


def render_page_frames(pages: list[dict[str, object]]) -> str:
    return "\n\n".join(render_page_frame(page, is_active=index == 0) for index, page in enumerate(pages))


def render_index(registry: dict[str, object]) -> str:
    site = registry.get("site")
    pages = registry.get("pages")
    if not isinstance(site, dict):
        raise ValueError("'site' must be an object in page-registry.json")
    if not isinstance(pages, list) or not pages:
        raise ValueError("'pages' must be a non-empty list in page-registry.json")

    title = escape(site.get("title") or "ChipBook")
    brand_title_html = str(site.get("brandTitleHtml") or title)
    subtitle = escape(site.get("subtitle") or "")
    total_pages = len(pages)

    return f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <link rel="icon" href="data:,">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Pretendard:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./assets/guidebook-common.css">
</head>
<body class="flex flex-col min-h-screen">
    <!-- Generated by tools/build_index.py from src/app/page-registry.json. -->
    <header class="bg-white sticky top-0 z-50 border-b border-gray-200 shadow-sm h-18">
        <div class="max-w-[2000px] mx-auto px-4 sm:px-6 lg:px-8 h-full flex items-center justify-between py-3">
            <div class="flex items-center gap-4">
                <div class="w-11 h-11 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-extrabold text-xl shadow-md">A</div>
                <div>
                    <span class="text-xl font-extrabold text-gray-900 tracking-tight block leading-tight">{brand_title_html}</span>
                    <span class="text-sm font-semibold text-gray-400">{subtitle}</span>
                </div>
            </div>
            <div class="text-sm font-semibold text-gray-500 hidden md:flex items-center gap-3 bg-gray-50 px-5 py-2.5 rounded-2xl border border-gray-100">
                <kbd class="bg-white px-2 py-1 rounded-lg border border-gray-200 shadow-sm font-mono text-gray-800 text-xs">←</kbd>
                <span>방향키로 이동</span>
                <kbd class="bg-white px-2 py-1 rounded-lg border border-gray-200 shadow-sm font-mono text-gray-800 text-xs">→</kbd>
            </div>
        </div>
    </header>

    <div class="max-w-[2000px] mx-auto flex flex-col lg:flex-row gap-10 mt-8 px-4 sm:px-6 lg:px-8 flex-1 w-full xl:items-start">
        <aside class="w-full lg:w-72 shrink-0 lg:sticky sidebar overflow-y-auto hidden lg:block pr-6 bg-transparent border-none">
            <h3 class="font-extrabold text-gray-400 mb-6 text-xs uppercase tracking-widest px-2">Table of Contents</h3>
            <nav class="space-y-1" id="toc-nav">
{render_nav(pages)}
            </nav>
        </aside>

        <main class="w-full lg:flex-1 min-w-0 relative pb-24">
{render_page_frames(pages)}

            <div class="mt-16 pt-8 border-t border-gray-200 flex justify-between items-center" id="page-controls">
                <button id="btn-prev" class="bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 px-6 py-3 rounded-xl font-bold shadow-sm transition-all flex items-center disabled:opacity-30 disabled:cursor-not-allowed">
                    <span class="mr-2">←</span> 이전 페이지
                </button>
                <span class="text-gray-400 font-bold text-sm" id="page-indicator">Page 1 of {total_pages}</span>
                <button id="btn-next" class="bg-blue-600 text-white hover:bg-blue-700 px-6 py-3 rounded-xl font-bold shadow-[0_4px_12px_rgba(49,130,246,0.3)] transition-all flex items-center disabled:opacity-30 disabled:cursor-not-allowed">
                    다음 페이지 <span class="ml-2">→</span>
                </button>
            </div>
        </main>

        <aside class="page-side-toc-shell hidden xl:block xl:w-72 2xl:w-80 shrink-0 xl:sticky xl:top-[6.5rem] self-start" data-page-toc-shell>
            <div class="page-side-toc-panel">
                <div class="page-side-toc-header">
                    <div class="page-side-toc-eyebrow">This Page</div>
                    <div class="page-side-toc-title" data-page-toc-title>이 페이지</div>
                </div>
                <nav class="page-side-toc-nav" data-page-toc-nav></nav>
                <div class="page-side-toc-empty" data-page-toc-empty>소목차를 불러오는 중입니다.</div>
            </div>
        </aside>
    </div>

    <script src="./assets/guidebook-main.js"></script>
</body>
</html>
"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build index.html from src/app/page-registry.json.")
    parser.add_argument("--check", action="store_true", help="Check index.html without rewriting it.")
    args = parser.parse_args(argv)

    try:
        rendered = render_index(load_registry())
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else None
        changed = current != rendered

        if args.check:
            print(f"[{'changed' if changed else 'ok'}] {INDEX_PATH.relative_to(REPO_ROOT)}")
            return 1 if changed else 0

        if changed:
            INDEX_PATH.write_text(rendered, encoding="utf-8", newline="")
        print(f"[{'changed' if changed else 'ok'}] {INDEX_PATH.relative_to(REPO_ROOT)}")
        return 0
    except Exception as error:  # pragma: no cover - CLI error handling
        print(f"build_index.py: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
